name: Bug report
description: File a bug report to help improve UNITE
labels: ["type:bug"]
body:
- type: textarea
  id: problem-description
  attributes:
    label: Describe the problem
    placeholder: |
      A clear and concise description of what you're experiencing.
  validations:
    required: true

- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to reproduce
    description: |
      A clear and concise description of what you're experiencing.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    placeholder: |
      A clear and concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  id: images-videos
  attributes:
    label: Screenshots or videos
    description: |
      Add screenshots or videos that show the bug here.
    placeholder: |
      Drag and drop the screenshots/videos into this box.
  validations:
    required: false

- type: input
  id: c4d-version
  attributes:
    label: Cinema 4D version used?
    description: |
      Tell us the version shown in the title of the C4D application
    placeholder: |
      (e.g R23.110)
  validations:
    required: true

- type: input
  id: unite-version
  attributes:
    label: UNITE version used?
    description: |
      Tell us the version you see in the null object called UNITE or the version number of your download if the one inside the null seems wrong.
    placeholder: |
      (e.g v0.1.1)
  validations:
    required: true

- type: checkboxes
  id: acknowledgements
  attributes:
    label: Acknowledgments
    description: |
      Please make sure you are able to tick the items below, so that all parties involved have an easier time.
      Your issue is very likely to be closed and ignored if these conditions are not met.
    options:
    - label: I tried a clean download and see the same problem
      required: true
    - label: I have searched the existing issues for a duplicate
      required: true